services:
  plex-curator:
    build: .
    container_name: plex-curator
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "5000:5000"
    env_file:
      - ./data/.env
    volumes:
      - ./themes:/opt/plex-curator/themes
      - ./data:/opt/plex-curator/data
      - ./templates:/opt/plex-curator/templates
      - ./src:/opt/plex-curator/src
    command:
      - bash
      - -c
      - |
        echo "Setting up cron job..."
        echo "0 0 1 * * cd /opt/plex-curator && python3 -m src.monthly >> /var/log/plex-curator-monthly.log 2>&1" > /etc/cron.d/plex-curator-monthly
        chmod 0644 /etc/cron.d/plex-curator-monthly
        crontab /etc/cron.d/plex-curator-monthly

        touch /var/log/plex-curator.log
        touch /var/log/plex-curator-monthly.log

        echo "Starting cron daemon..."
        service cron start

        echo "Starting Flask web UI on port 5000..."
        python3 -m src.webui
